name = "Dream Plus"
license = "MIT"
licenselink = "https://github.com/UtkarshVerma/hugo-dream-plus/blob/master/LICENSE"
description = "An upgraded version of the hugo-dream-theme with tons of new features."
homepage = "https://github.com/UtkarshVerma/hugo-dream-plus"
tags = ["clean", "blog", "single page", "responsive", "google analytics","disqus", "personal", "syntax highlighting", "single page", "mobile"]
features = ["randomBackground","favicon","blurBackground","home cards","flip", "colorful", "imagebackground", "i18n", "copyright", "motto"]
min_version = "0.48"

[author]
	name = "Utkarsh Verma"
	homepage = "https://utkarshverma.github.io"

[original]
	name = "UtkarshVerma's Blog"
	homepage = "https://utkarshverma.github.io"
	repo = "https://github.com/UtkarshVerma/utkarshverma.github.io"
