baseURL = "https://dream-plus-cards.netlify.com"
title = "UtkarshVerma's Site"
theme = "dream-plus"
themesDir = "../.."		#Don't use this, only for exampleSite
paginate = 4
enableRobotsTXT = true

#Skip building these files
ignoreFiles = ["content/404.md", "content/about.md", "content/posts/\\.*"]

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	#Favicon for site
	favicon = "/img/defaultFav.ico"

	#Set whether you're hosting "cards" or "post"
	contentType = "cards"
	
	siteStartYear = 2018

	[params.author]
		name = "Utkarsh Verma"
		description = "Just a random blog for random stuff, mostly tech-related."
		avatar = "https://raw.githubusercontent.com/UtkarshVerma/utkarshverma.github.io/source/static/images/avatar.jpg"
		motto = "A keen maker, programmer and an Instructables author."

	[params.features]
		#Enable Twitter Emoji
		twitterEmoji = true
		#Enable Table of Contents
		toc = true
		#Enable share card
		shareCard = true
		#Use custom CSS
		customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	[params.background]
		colorBG = true

[social]
	email = "utkarshverma@pm.me"
	github = "UtkarshVerma"
	stackoverflow = "9271608/utkarsh-verma"
	medium = "UtkarshVerma_"
	twitter = "UtkarshVerma_"
