baseURL = "https://utkarshverma.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "UtkarshVerma's Site"
theme = "dream-plus"
themesDir = "../../"   #Don't use this, only for netlify

googleAnalytics = "UA-112332904-3"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
  author = "Utkarsh Verma"
  description = "A hub for my works."
  avatar = "https://raw.githubusercontent.com/UtkarshVerma/blog/source/static/images/myavatar.jpg"
  motto = "A keen maker, programmer and an Instructables author."

  favicon = "/img/defaultFav.ico"

  #Background Settings
  enableColorBG = true

  #Cards shown per page
  itemsPerPage = 4

  #Enable card view
  contentType = "cards"

  #Enable Twitter Emoji
  twitterEmoji=true

[social]
  email = "utkarshverma@pm.me"
  github = "UtkarshVerma"
  stackoverflow = "9271608/utkarsh-verma"
  medium = "UtkarshVerma_"
  twitter = "UtkarshVerma_"
  siteStartYear = 2018
