baseURL = "http://dream-plus.netlify.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "UtkarshVerma's Blog"
theme = "dream-plus"
themesDir = "../../"   #Don't use this, only for netlify

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "dream-plus"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Utkarsh Verma"
	description = "Just a random blog for random stuff, mostly tech-related."
	avatar = "https://raw.githubusercontent.com/UtkarshVerma/blog/source/static/images/myavatar.jpg"
	motto = "A keen maker, programmer and an Instructables author."
	enableToc = true
	enableShareCard = true

	favicon = "/img/defaultFav.ico"

  	#Background settings
	enableColorBG= true

	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	#Cards or posts shown per page
	itemsPerPage = 4

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	#Enable Twitter Emoji
	twitterEmoji=true

[social]
	email = "utkarshverma@pm.me"
	github = "UtkarshVerma"
	stackoverflow = "9271608/utkarsh-verma"
	medium = "UtkarshVerma_"
	twitter = "UtkarshVerma_"
	siteStartYear = 2018